
SELECTION-SCREEN BEGIN OF BLOCK valorPedido WITH FRAME TITLE text-001.

PARAMETERS p_valorpedido TYPE p DECIMALS 2.

SELECTION-SCREEN END OF BLOCK valorPedido.



SELECTION-SCREEN BEGIN OF BLOCK itens WITH FRAME TITLE text-002.

PARAMETERS p_qtditens TYPE i.

SELECTION-SCREEN END OF BLOCK itens.




SELECTION-SCREEN BEGIN OF BLOCK entrega WITH FRAME TITLE text-003.

PARAMETERS p_entreganormal RADIOBUTTON GROUP g1,
           p_entregaexpressa RADIOBUTTON GROUP g1,
           p_entregaurgente RADIOBUTTON GROUP g1.

SELECTION-SCREEN END OF BLOCK entrega.

