

SELECTION-SCREEN BEGIN OF BLOCK nota1 WITH FRAME TITLE text-001.

PARAMETERS p_nota1 TYPE f VALUE = 0.

SELECTION-SCREEN END OF BLOCK nota1.


SELECTION-SCREEN BEGIN OF BLOCK nota2 WITH FRAME TITLE text-002.

PARAMETERS p_nota2 TYPE f VALUE = 0.

SELECTION-SCREEN END OF BLOCK nota2.


SELECTION-SCREEN BEGIN OF BLOCK nota3 WITH FRAME TITLE text-003.

PARAMETERS p_nota3 TYPE f VALUE = 0.

SELECTION-SCREEN END OF BLOCK nota3.


SELECTION-SCREEN BEGIN OF BLOCK nota4 WITH FRAME TITLE text-04.

PARAMETERS p_nota4 TYPE f VALUE = 0.

SELECTION-SCREEN END OF BLOCK nota4.



       