SELECTION-SCREEN BEGIN OF BLOCK oper WITH FRAME TITLE text-001.

PARAMETERS: p_op1  TYPE i,
            p_op2  TYPE i.

SELECTION-SCREEN END OF BLOCK oper.


SELECTION-SCREEN BEGIN OF BLOCK operacao WITH FRAME TITLE text-002.

PARAMETERS: p_adic RADIOBUTTON GROUP g1,
            p_mult RADIOBUTTON GROUP g1,
            p_div  RADIOBUTTON GROUP g1,
            p_sub  RADIOBUTTON GROUP g1,
            p_test  TYPE ABAP_BOOL AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK operacao.